# Site settings
title: "Shadow"
tagline: "real applications, simulated networks"
#Google analytics code in the format XX-nnnnnnnn-n
analytics: UA-18979348-4
baseurl: "" #important: start with /
url: "https://shadow.github.io/"
description: "Shadow is a unique discrete-event network simulator that runs real applications like Tor, and distributed systems of thousands of nodes on a single machine. Shadow combines the accuracy of emulation with the efficiency and control of simulation, achieving the best of both approaches."

# Build settings
markdown: kramdown

colors:  #in hex code if not noted else
  primary: "#2b5c70"
  secondary: "#1c212b"
  link: "#60c1c4"
  link_hover: "#d5f5eb"
  footer_heading: "#ffffff"
  footer_content: "#2b5c70"

# Users information
users:
  - name: nrl
    img: nrl.png
    url: https://www.nrl.navy.mil/itd/chacs/5543
  - name: umn
    img: umn.png
    url: https://www-users.cs.umn.edu/~hopper/
  - name: georgetown
    img: gu.png
    url: https://security.cs.georgetown.edu/
  - name: kuleuven
    img: kul.png
    url: http://www.esat.kuleuven.be/cosic/
  - name: tor
    img: tor.png
    url: https://www.torproject.org/
  - name: cambridge
    img: cambridge.png
    url: https://www.cl.cam.ac.uk/research/security
  - name: uiuc
    img: uiuc.png
    url: http://hatswitch.org/~nikita
  - name: tudarmstadt
    img: tud.png
    url: 
  - name: wesleyan
    img: wesleyan.png
    url: http://ndanner.web.wesleyan.edu/
    
