# Site settings
title: "Shadow"
tagline: "real applications, simulated networks"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://shadow.github.io"

# Build settings
markdown: kramdown

colors:  #in hex code if not noted else
  primary: "#2b5c70"
  secondary: "#1c212b"
  link: "#60c1c4"
  link_hover: "#d5f5eb"
  footer_heading: "#ffffff"
  footer_content: "#2b5c70"

# Users information
users:
  - name: nrl
    img: nrl.png
    url: https://www.nrl.navy.mil/itd/chacs/5543
  - name: umn
    img: umn.jpg
    url: https://www-users.cs.umn.edu/~hopper/
  - name: georgetown
    img: georgetown.png
    url: https://security.cs.georgetown.edu/
  - name: kuleuven
    img: kuleuven.png
    url: http://www.esat.kuleuven.be/cosic/
  - name: tor
    img: tor.jpg
    url: https://www.torproject.org/
  - name: cambridge
    img: cambridge.gif
    url: https://www.cl.cam.ac.uk/research/security
  - name: uiuc
    img: uiuc.gif
    url: http://hatswitch.org/~nikita
  - name: tudarmstadt
    img: tudarmstadt.png
    url: 
  - name: wesleyan
    img: wesleyan.gif
    url: 
    
